import { randomUUID } from "node:crypto";

/**
 * Creates a UUIDv4 for any entity. IDs are always generated by the application, never by the
 * database. Lives in the domain package (rather than @kaada/utils) because entities need it and the
 * domain must not depend on other workspace packages.
 */
export function createId(): string {
  return randomUUID();
}

const UUID_PATTERN = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

export function isUuid(value: unknown): value is string {
  return typeof value === "string" && UUID_PATTERN.test(value);
}
